env-file: .envs/.django
groups:
  reactjs:
    tasks:
      install:
        help: Install the dependencies for the frontend
        dir: src/frontend
        run: npm install
      build:
        help: Build the assets for reactjs
        dir: src/frontend
        run: npm run build
      autobuild:
        help: Build the assets for reactjs
        run: python scripts/autobuild_frontend.py

  django:
    tasks:
      runserver:
        env-file: .envs/.env
        hooks:
          pre-run:
            - task: reactjs.install
            - task: reactjs.build
        dir: src/backend
        run: |
          if "${{ env.SUGAR_GROUP }}" == "prod":
              python manage.py compress
          python manage.py runserver

      migrate:
        env-file: .envs/.env
        dir: src/backend
        run: |
          python manage.py migrate

      collectstatic:
        env-file: .envs/.env
        dir: src/backend
        hooks:
          pre-run:
            - task: reactjs.install
            - task: reactjs.build
        run: |
          python manage.py collectstatic -v 3 --noinput  # --clear

  release:
    vars:
      app: |
        npx --yes \
          -p semantic-release \
          -p conventional-changelog-conventionalcommits \
          -p "@semantic-release/commit-analyzer" \
          -p "@semantic-release/release-notes-generator" \
          -p "@semantic-release/changelog" \
          -p "@semantic-release/exec" \
          -p "@semantic-release/github" \
          -p "@semantic-release/git" \
          -p "semantic-release-replace-plugin@1.2.7" \
          semantic-release

    tasks:
      ci:
        help: run semantic release on CI
        run: ${{ vars.app }} --ci

      dry:
        help: run semantic release in dry-run mode
        run: |
          ${{ vars.app }} --dry-run
