env-file: .envs/.django
groups:
  django:
    tasks:
      runserver:
        env-file: .envs/.env
        dir: src/backend
        run: |
          python manage.py runserver

      migrate:
        env-file: .envs/.env
        dir: src/backend
        run: |
          python manage.py migrate

      collectstatic:
        env-file: .envs/.env
        dir: src/backend
        run: |
          python manage.py collectstatic
