version: 1.0
compose-app: docker compose
env-file: .envs/.env
defaults:
  group: ${{ env.SUGAR_GROUP }}
  project-name: mhai
groups:
  dev:
    compose-path:
      - containers/compose.base.yaml
      - containers/compose.dev.yaml
    env-file: .envs/.env
    services:
      default: postgres,mailpit,redis,celeryworker,celerybeat,flower
      available:
        - name: mhai-web
        - name: postgres
        - name: mailpit
        - name: redis
        - name: celeryworker
        - name: celerybeat
        - name: flower

  prod:
    compose-path:
      - containers/compose.base.yaml
      - containers/compose.prod.yaml
    env-file: .envs/.env
    services:
      default: postgres,redis,celeryworker,celerybeat,flower,traefik,nginx
      available:
        - name: mhai-web
        - name: postgres
        - name: redis
        - name: celeryworker
        - name: celerybeat
        - name: flower
        - name: traefik
        - name: nginx
