volumes:
  postgres_data: {}
  postgres_data_backups: {}
  redis_data: {}

services:
  mhai-web:
    volumes:
      - .:/app:z

  mailpit:
    image: docker.io/axllent/mailpit:latest
    hostname: mailpit
    ports:
      - "${MAILPIT_PORT:-8025}:${MAILPIT_PORT:-8025}"

  celeryworker:
    volumes:
      - .:/app:z

  celerybeat:
    volumes:
      - .:/app:z

  flower:
    volumes:
      - .:/app:z
