volumes:
  traefik: {}
  mhai_web_media: {}

services:
  mhai-web-base:
    build:
      context: ..
      # note: we need to move that to the prod dockerfile
      dockerfile: ./containers/django/dev/Dockerfile

  traefik:
    build:
      context: ..
      dockerfile: ./containers/traefik/Dockerfile
    image: mhai-traefik
    depends_on:
      - mhai-web
    volumes:
      - traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  nginx:
    build:
      context: ..
      dockerfile: ./containers/nginx/Dockerfile
    image: mhai-nginx
    depends_on:
      - mhai-web
    volumes:
      - mhai_web_media:/usr/share/nginx/media:ro
