volumes:
  postgres_data: {}
  postgres_data_backups: {}
  traefik: {}
  django_media: {}

  redis_data: {}

services:
  mhai-web-base:
    build:
      context: ..
      dockerfile: ./containers/django/production/Dockerfile

  traefik:
    build:
      context: ..
      dockerfile: ./containers/traefik/Dockerfile
    image: mhai-traefik
    depends_on:
      - django
    volumes:
      - traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  nginx:
    build:
      context: ..
      dockerfile: ./containers/nginx/Dockerfile
    image: mhai-nginx
    depends_on:
      - mhai_web
    volumes:
      - mhai_web_media:/usr/share/nginx/media:ro
