# Generated by Django 5.1.2 on 2024-10-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('O', 'Other'), ('C', 'Custom')], default='O', max_length=2)),
                ('gender_custom', models.CharField(blank=True, max_length=50, null=True)),
                ('interests', models.TextField(max_length=1000)),
                ('emotional_profile', models.TextField(max_length=1000)),
                ('bio_life', models.TextField(max_length=4000)),
                ('bio_education', models.TextField(max_length=4000)),
                ('bio_work', models.TextField(max_length=4000)),
                ('bio_family', models.TextField(max_length=4000)),
                ('bio_friends', models.TextField(max_length=4000)),
                ('bio_pets', models.TextField(max_length=4000)),
                ('bio_health', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileImportantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('impact', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('treated', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_events', to='user_profile.userprofile')),
            ],
        ),
    ]
