# Generated by Django 5.1.2 on 2024-11-02 02:07

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("NB", "Non-Binary"),
                            ("O", "Other"),
                            ("C", "Custom"),
                        ],
                        default="O",
                        max_length=2,
                    ),
                ),
                ("gender_custom", models.CharField(blank=True, max_length=50)),
                ("interests", models.TextField(max_length=1000)),
                ("emotions", models.TextField(max_length=1000)),
                ("bio_life", models.TextField(max_length=4000)),
                ("bio_education", models.TextField(max_length=4000)),
                ("bio_work", models.TextField(max_length=4000)),
                ("bio_family", models.TextField(max_length=4000)),
                ("bio_friends", models.TextField(max_length=4000)),
                ("bio_pets", models.TextField(max_length=4000)),
                ("bio_health", models.TextField(max_length=4000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
