# Generated by Django 5.1.3 on 2024-12-12 14:06

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_plotly_dash", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatelessApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=110, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DashApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_name",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=110, unique=True),
                ),
                ("base_state", models.TextField(default="{}")),
                ("creation", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                ("save_on_change", models.BooleanField(default=False)),
                (
                    "stateless_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dash_instances",
                        to="dashboards.statelessapp",
                    ),
                ),
            ],
        ),
    ]
