# Generated by Django 5.1.5 on 2025-02-26 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MhaiDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('prompt_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField()),
                ('response_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error')], default='started', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prompt_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MhaiDiaryEvalEmotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neutral', models.FloatField()),
                ('joy', models.FloatField()),
                ('disgust', models.FloatField()),
                ('sadness', models.FloatField()),
                ('anger', models.FloatField()),
                ('surprise', models.FloatField()),
                ('fear', models.FloatField()),
                ('my_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_diary.mhaidiary')),
            ],
        ),
        migrations.CreateModel(
            name='MhaiDiaryEvalMentBert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borderline', models.FloatField()),
                ('anxiety', models.FloatField()),
                ('depression', models.FloatField()),
                ('bipolar', models.FloatField()),
                ('ocd', models.FloatField()),
                ('adhd', models.FloatField()),
                ('schizophrenia', models.FloatField()),
                ('asperger', models.FloatField()),
                ('ptsd', models.FloatField()),
                ('my_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_diary.mhaidiary')),
            ],
        ),
        migrations.CreateModel(
            name='MhaiDiaryEvalPsychBert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unrelated', models.FloatField()),
                ('mental_illnesses', models.FloatField()),
                ('anxiety', models.FloatField()),
                ('depression', models.FloatField()),
                ('social_anxiety', models.FloatField()),
                ('loneliness', models.FloatField()),
                ('my_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_diary.mhaidiary')),
            ],
        ),
    ]
