# Generated by Django 5.1.2 on 2024-11-12 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MhaiChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('ai_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MhaiChatEvalEmotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neutral', models.FloatField()),
                ('joy', models.FloatField()),
                ('disgust', models.FloatField()),
                ('sadness', models.FloatField()),
                ('anger', models.FloatField()),
                ('surprise', models.FloatField()),
                ('fear', models.FloatField()),
                ('mhai_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhai_chat.mhaichat')),
            ],
        ),
        migrations.CreateModel(
            name='MhaiChatEvalMentBert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borderline', models.FloatField()),
                ('anxiety', models.FloatField()),
                ('depression', models.FloatField()),
                ('bipolar', models.FloatField()),
                ('ocd', models.FloatField()),
                ('adhd', models.FloatField()),
                ('schizophrenia', models.FloatField()),
                ('asperger', models.FloatField()),
                ('ptsd', models.FloatField()),
                ('mhai_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhai_chat.mhaichat')),
            ],
        ),
        migrations.CreateModel(
            name='MhaiChatEvalPsychBert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unrelated', models.FloatField()),
                ('mental_illnesses', models.FloatField()),
                ('anxiety', models.FloatField()),
                ('depression', models.FloatField()),
                ('social_anxiety', models.FloatField()),
                ('loneliness', models.FloatField()),
                ('mhai_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mhai_chat.mhaichat')),
            ],
        ),
    ]
